openapi: 3.0.4
info:
  title: Swagger Editor msvc
  description: This is a Swagger spec for the code editor.
  license:
    name: Apache 2.0
  version: 1.0.12

tags:
  - name: editor
    description: Everything about Editor

paths:
  /template:
    get:
      tags:
        - editor
      summary: Get Template of zip
      operationId: getTemplate
      parameters:
        - in: query
          name: problemNo
          required: true
          schema:
            type: string
            example: "1"
          description: Get items e.g., problemNo=1
      responses:
        '206':
          description: Partial Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '400':
          description: Invalid request
        '404':
          description: Not found
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Template:
      type: object
      properties:
        codeSetupZip:
          type: string
          format: binary
          description: Zip file containing Code Setup/Code Done Till Now

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "VALIDATION_FAILED"
        message:
          type: string
          example: "Invalid input provided"
